=== trushank/Java/Radix Sort/pets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/pets" xmlns:tns="http://www.example.org/pets" elementFormDefault="qualified">


    <complexType name="pets">
    	<sequence>
    		<element name="dogs" type="tns:dogs"></element>
    		<element name="cats" type="tns:cats"></element>
    	</sequence>
    </complexType>
    
    <complexType name="dogs">
    	<sequence>
    		<element name="dog" type="tns:dog" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="cats">
    	<sequence>
    		<element name="cat" type="tns:cat" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="dog">
    	<sequence>
    		<element name="color" type="string"></element>
    	</sequence>
    	<attribute name="breed" type="string"></attribute>
    </complexType>

    <complexType name="cat">
    	<sequence>
    		<element name="color" type="string"></element>
    	</sequence>
    	<attribute name="breed" type="string"></attribute>
    </complexType>

    <element name="pets" type="tns:pets"></element>
</schema>

=== trushank/Java/Radix Sort/pets.xml
<?xml version="1.0"?>

<pets
    xmlns="http://www.example.org/pets"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.example.org/pets pets.xsd">
  <dogs>
    <dog breed="Labrador">
      <color>Black</color>
    </dog>
    <dog breed="Labrador">
      <color>Golden</color>
    </dog>
  </dogs>
  <cats>
    <cat breed='Siamese'>
      <color>Cream</color>
    </cat>
    <cat breed='Burmese'>
      <color>Grey</color>
    </cat>
    <cat breed='Tortoiseshell'>
      <color>Brown</color>
    </cat>
  </cats>
</pets>
